spring:
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:26666/reporting?sslmode=disable
    username: root
    password:
    hikari:
      auto-commit: true
      idle-timeout: 50000
      minimum-idle: 2
      maximum-pool-size: 8
      max-lifetime: 200000
      connection-timeout: 5000
      keepalive-time: 60000
      validation-timeout: 3000
      data-source-properties:
        reWriteBatchedInserts: true # This should speedup inserts
